version: '3.8'

services:


  database:
    build: .
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpsswrd'
    ports:
      - '6033:3306'
    expose:
      - '3306'
    volumes:
       - /var/lib/docker/volumes/alphaqdb71:/var/lib/mysql
       - /var/lib/docker/volumes/alphaqserver71:/home/Documents/delta

  web-server:
    build: ./web
    restart: always
    volumes:
      - /var/lib/docker/volumes/alphaqhtml71:/var/www/html
    ports:
      - "8080:80"

 

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - database
    container_name: phpmyadmin
    restart: always
    ports:
      - '5000:80'
    environment:
      PMA_HOST: database